root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/main.go"
pre_cmd = ["templ generate"]
bin = "./tmp/main"
include_ext = ["go", "templ"]
exclude_dir = ["tmp", "node_modules"]
exclude_regex = [".*_templ\\.go$"]
delay = 1000
stop_on_error = true

[watch]
paths = ["./templates"]

